export const dummyNotes = [
  {
    id: 1,
    title: "Grocery Shopping",
    content: "Buy milk, eggs, bread, and apples from the store",
    content_html: "<p>Buy <strong>milk</strong>, eggs, bread, and apples from the store</p>",
    type: "note",
    status: "active",
    tags: "shopping,groceries",
    metadata: JSON.stringify({ category: "personal", color: "#ff6b6b" }),
    image_path: null,
    image_blob: null,
    priority: 2,
    last_viewed: "2024-01-15 10:30:00",
    reminder_at: "2024-01-16 09:00:00",
    completed_at: null,
    due_date: "2024-01-16",
    created_at: "2024-01-15 08:15:00",
    updated_at: "2024-01-15 10:30:00",
  },
  {
    id: 2,
    title: "Meeting Notes",
    content: "Discussed project timeline and deliverables with team",
    content_html: "<p>Discussed <em>project timeline</em> and deliverables with team</p>",
    type: "note",
    status: "active",
    tags: "work,meeting",
    metadata: JSON.stringify({ attendees: ["John", "Sarah"], duration: "1h" }),
    image_path: "/storage/meeting_whiteboard.jpg",
    image_blob: null,
    priority: 3,
    last_viewed: "2024-01-15 14:20:00",
    reminder_at: null,
    completed_at: null,
    due_date: null,
    created_at: "2024-01-15 13:45:00",
    updated_at: "2024-01-15 14:20:00",
  },
  {
    id: 3,
    title: "Workout Plan",
    content: "30 min cardio, 20 min strength training, 10 min stretching",
    content_html:
      "<p><strong>30 min</strong> cardio, <strong>20 min</strong> strength training, <strong>10 min</strong> stretching</p>",
    type: "task",
    status: "completed",
    tags: "fitness,health",
    metadata: JSON.stringify({ calories_burned: 350, equipment: "gym" }),
    image_path: null,
    image_blob: null,
    priority: 1,
    last_viewed: "2024-01-14 18:00:00",
    reminder_at: null,
    completed_at: "2024-01-14 18:00:00",
    due_date: "2024-01-14",
    created_at: "2024-01-14 06:00:00",
    updated_at: "2024-01-14 18:00:00",
  },
  {
    id: 4,
    title: "Book Recommendation",
    content: "Read 'The Pragmatic Programmer' - great insights on software development",
    content_html:
      "<p>Read <cite>'The Pragmatic Programmer'</cite> - great insights on software development</p>",
    type: "note",
    status: "active",
    tags: "books,programming,learning",
    metadata: JSON.stringify({ author: "David Thomas", pages: 352, rating: 5 }),
    image_path: null,
    image_blob: null,
    priority: 1,
    last_viewed: "2024-01-13 20:15:00",
    reminder_at: null,
    completed_at: null,
    due_date: null,
    created_at: "2024-01-13 20:15:00",
    updated_at: "2024-01-13 20:15:00",
  },
  {
    id: 5,
    title: "Doctor Appointment",
    content: "Annual checkup with Dr. Smith at 2 PM",
    content_html: "<p>Annual checkup with <strong>Dr. Smith</strong> at <time>2 PM</time></p>",
    type: "task",
    status: "active",
    tags: "health,appointment",
    metadata: JSON.stringify({
      doctor: "Dr. Smith",
      clinic: "City Medical Center",
      phone: "555-0123",
    }),
    image_path: null,
    image_blob: null,
    priority: 3,
    last_viewed: "2024-01-15 11:00:00",
    reminder_at: "2024-01-17 13:00:00",
    completed_at: null,
    due_date: "2024-01-17",
    created_at: "2024-01-10 16:30:00",
    updated_at: "2024-01-15 11:00:00",
  },
];
